# Header
menu:
  Home: '/'
  Archives: '/archives'
  RSS: /atom.xml
  # Home:
  #   title: Home
  #   url: /
  #   icon: home
  # About:
  #   title: About
  #   url: /about
  #   icon: list-alt
  # Archives:
  #   title: Archives
  #   url: /archives
  #   icon: pencil
  # RSS:
  #   title: RSS
  #   url: /atom.xml
  #   icon: rss
  # Gitlab:
  #   title: Gitlab
  #   url: https://gitlab.coupang.net/phiphi
  #   icon: gitlab
  # Github:
  #   title: Github
  #   url: https://github.com/CSS-Org
  #   icon: github

# Title on top left of menu. Leave empty to use main blog title
menu_title:

# URL of the Home page image
index_cover: /img/logo.jpg

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: raopjs
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Addthis ID
addthis:

# Social Accounts
twitter_url:
twitter_handle:
facebook_url:
github_url: https://github.com/CSS-Org
gitlab_url: https://gitlab.coupang.net/phiphi
linkedin_url:
mailto: phiphi@coupang.com
